services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llmos
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    command: ["./llmos"]